STROKE_KEY_WORDS = ["инсульт"]
HYPERTENSION_KEY_WORDS = ["гипертензия"]
DIABETES_KEY_WORDS = ["диабет"]
HEART_FAILURE_KEY_WORDS = ["недостаточность"]
VASCULAR_DISEASE_KEY_WORDS = ["инфаркт", "атеросклероз", "бляшки"]
